# # PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lifestyle_articles_development
  username: lifestyle_articles
  password: lifestyle_12782
  host: localhost
  port: 5432

test:
  <<: *default
  database: lifestyle_articles_test
  host: localhost
  port: 5432
  username: lifestyle_articles
  password: lifestyle_12782

production:
  <<: *default
  database: lifestyle_articles_production
  username: lifestyle_articles
  password: <%= ENV['LIFESTYLE_ARTICLES_PASSWORD'] %>
